spring:
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/products
    username: gb
    password: geekbrains
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  thymeleaf:
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/